apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kai-scheduler
    meta.helm.sh/release-namespace: kai-scheduler
  creationTimestamp: "2025-07-23T09:10:53Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: scheduler
  namespace: kai-scheduler
  resourceVersion: "403129"
  uid: 852914d5-287f-4748-a587-0b46010b1da0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scheduler
    spec:
      containers:
      - args:
        - --scheduler-conf=/etc/config/config.yaml
        - --namespace=kai-scheduler
        - --resource-reservation-app-label=kai-resource-reservation
        image: ghcr.io/nvidia/kai-scheduler/scheduler:v0.7.8
        imagePullPolicy: IfNotPresent
        name: scheduler
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config/config.yaml
          name: config
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: scheduler
      serviceAccountName: scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: scheduler-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-23T09:10:53Z"
    lastUpdateTime: "2025-07-23T09:11:00Z"
    message: ReplicaSet "scheduler-545c4cb55c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-25T02:06:20Z"
    lastUpdateTime: "2025-07-25T02:06:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
